using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[System.Serializable]
public class SideObservation : MonoBehaviour
{
    string[,] m_ObservedColors;
    [SerializeField] string slot1Height1 = null;
    [SerializeField] string slot1Height2 = null;
    [SerializeField] string slot1Height3 = null;
    [SerializeField] string slot1Height4 = null;
    [SerializeField] string slot1Height5 = null;
    [SerializeField] string slot1Height6 = null;
    [SerializeField] string slot1Height7 = null;
    [SerializeField] string slot1Height8 = null;
    [SerializeField] string slot2Height1 = null;
    [SerializeField] string slot2Height2 = null;
    [SerializeField] string slot2Height3 = null;
    [SerializeField] string slot2Height4 = null;
    [SerializeField] string slot2Height5 = null;
    [SerializeField] string slot2Height6 = null;
    [SerializeField] string slot2Height7 = null;
    [SerializeField] string slot2Height8 = null;
    [SerializeField] string slot3Height1 = null;
    [SerializeField] string slot3Height2 = null;
    [SerializeField] string slot3Height3 = null;
    [SerializeField] string slot3Height4 = null;
    [SerializeField] string slot3Height5 = null;
    [SerializeField] string slot3Height6 = null;
    [SerializeField] string slot3Height7 = null;
    [SerializeField] string slot3Height8 = null;
    [SerializeField] string slot4Height1 = null;
    [SerializeField] string slot4Height2 = null;
    [SerializeField] string slot4Height3 = null;
    [SerializeField] string slot4Height4 = null;
    [SerializeField] string slot4Height5 = null;
    [SerializeField] string slot4Height6 = null;
    [SerializeField] string slot4Height7 = null;
    [SerializeField] string slot4Height8 = null;
    [SerializeField] string slot5Height1 = null;
    [SerializeField] string slot5Height2 = null;
    [SerializeField] string slot5Height3 = null;
    [SerializeField] string slot5Height4 = null;
    [SerializeField] string slot5Height5 = null;
    [SerializeField] string slot5Height6 = null;
    [SerializeField] string slot5Height7 = null;
    [SerializeField] string slot5Height8 = null;
    [SerializeField] string slot6Height1 = null;
    [SerializeField] string slot6Height2 = null;
    [SerializeField] string slot6Height3 = null;
    [SerializeField] string slot6Height4 = null;
    [SerializeField] string slot6Height5 = null;
    [SerializeField] string slot6Height6 = null;
    [SerializeField] string slot6Height7 = null;
    [SerializeField] string slot6Height8 = null;
    [SerializeField] string slot7Height1 = null;
    [SerializeField] string slot7Height2 = null;
    [SerializeField] string slot7Height3 = null;
    [SerializeField] string slot7Height4 = null;
    [SerializeField] string slot7Height5 = null;
    [SerializeField] string slot7Height6 = null;
    [SerializeField] string slot7Height7 = null;
    [SerializeField] string slot7Height8 = null;
    [SerializeField] string slot8Height1 = null;
    [SerializeField] string slot8Height2 = null;
    [SerializeField] string slot8Height3 = null;
    [SerializeField] string slot8Height4 = null;
    [SerializeField] string slot8Height5 = null;
    [SerializeField] string slot8Height6 = null;
    [SerializeField] string slot8Height7 = null;
    [SerializeField] string slot8Height8 = null;
    [SerializeField] string slot9Height1 = null;
    [SerializeField] string slot9Height2 = null;
    [SerializeField] string slot9Height3 = null;
    [SerializeField] string slot9Height4 = null;
    [SerializeField] string slot9Height5 = null;
    [SerializeField] string slot9Height6 = null;
    [SerializeField] string slot9Height7 = null;
    [SerializeField] string slot9Height8 = null;
}
